// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (AuthIdentity, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error)
	GetIdentityByProvider(ctx context.Context, arg GetIdentityByProviderParams) (AuthIdentity, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error)
}

var _ Querier = (*Queries)(nil)
