// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (AuthIdentity, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (AuthRefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error)
	GetIdentityByProvider(ctx context.Context, arg GetIdentityByProviderParams) (AuthIdentity, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (AuthRefreshToken, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error)
	ListUserRefreshTokens(ctx context.Context, userID uuid.UUID) ([]AuthRefreshToken, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) error
}

var _ Querier = (*Queries)(nil)
